<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
fasdfasdfasdf<?php print_r(333);?>{$test_str.oo}---{$test_str1['ff']}---{$test_str2}---{$test_str}---{$test_str}
{333}{$test_str1 + $tetdd}
{if $array>22}fff{else}ffff{/if}

<eq name="$item['tess']" value="212">
    <eq name="$test" value="12">
fasdf1
        <eq name="$test" value="12">
            fasdf10

        </eq>
    </eq>fasdfasd2
<else />
</eq>
<eq name="$item['tess']" value="212">fff
    <else />eeee
</eq>

<neq name="$test_str.oo"  value="12">fsdfds3
</neq>
<neq name="$test" value="121">fsdfsad4
    <gt name="$test" value="12">sdfsadfd5
    </gt>fsdfasd6
</neq>
</body>
</html>